// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Fri Sep 15 19:06:20 2023

controlador_frere_jacque controlador_frere_jacque_inst
(
	.Clk_out(Clk_out_sig) ,	// output  Clk_out_sig
	.Disparo(Disparo_sig) ,	// output  Disparo_sig
	.Temp_out(Temp_out_sig) ,	// output [27:0] Temp_out_sig
	.Freq_out(Freq_out_sig) ,	// output [27:0] Freq_out_sig
	.Clk_in(Clk_in_sig) ,	// input  Clk_in_sig
	.Duracao(Duracao_sig) ,	// input  Duracao_sig
	.Stop_in(Stop_in_sig) ,	// input  Stop_in_sig
	.Play_in(Play_in_sig) 	// input  Play_in_sig
);

