// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Fri Sep 22 08:56:24 2023

horizontal_sync horizontal_sync_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.hsync(hsync_sig) ,	// output  hsync_sig
	.hcount(hcount_sig) ,	// output [9:0] hcount_sig
	.hcount_ov(hcount_ov_sig) ,	// output  hcount_ov_sig
	.dat_act_h(dat_act_h_sig) 	// output  dat_act_h_sig
);

defparam horizontal_sync_inst.hsync_pulse = 'b0001100000;
defparam horizontal_sync_inst.hback_porch = 'b0000110000;
defparam horizontal_sync_inst.hfront_porch = 'b0000010000;
defparam horizontal_sync_inst.hresolution = 'b1010000000;
