// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Fri Sep 22 08:56:57 2023

vertical_sync vertical_sync_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.hcount_ov(hcount_ov_sig) ,	// input  hcount_ov_sig
	.vsync(vsync_sig) ,	// output  vsync_sig
	.vcount(vcount_sig) ,	// output [9:0] vcount_sig
	.dat_act_v(dat_act_v_sig) 	// output  dat_act_v_sig
);

defparam vertical_sync_inst.vsync_pulse = 'b0000000010;
defparam vertical_sync_inst.vback_porch = 'b0000011111;
defparam vertical_sync_inst.vfront_porch = 'b0000001011;
defparam vertical_sync_inst.vresolution = 'b0111100000;
